# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 17, 12, 47, 27973)),
        ),
    ]
