# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170911_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 17, 14, 39, 260567)),
        ),
    ]
