# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170911_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 18, 16, 21, 18, 30777)),
        ),
    ]
